name: CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    env:
      NIM_VERSION: '1.2.6'
    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ env.NIM_VERSION }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install nim dependencies
      run: nimble build -y
    - name: Install python dependencies
      run: python -m pip install wheel setuptools
    - name: Build nim files
      run: nimble release
    - name: Build python files
      run: nimble package
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: glm
        path: dist/*
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
    - name: GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: 'dist/*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
